name: Run Script with API Key

on:
  push:
    branches: [ "main" ]

jobs:
  run-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run script
        env:
          MY_API_KEY: ${{ secrets.API_KEY }}
        run: echo "The API Key is securely loaded into the background!"
